<a href="https://colab.research.google.com/github/kuznechek/FirstSteps/blob/master/GradientDescentWithSplitStep_ipynb%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Градиентный спуск с дроблением шага

Исходные параметры:

Одномерный тензор Х = (0.686, 2.164, 0.137)

Шаг = 0.001, коэффициент дробления = 0.7

Заданная точность = 0.1

In [57]:
import torch

def function(w):
  w1 = w[0] 
  w2 = w[1]
  w3 = w[2]
  result = 3 *w1**2 + w2**2 + 5*w3 - w1*w2 + 2*w1*w3 + 6*w1 - 5*w2
  return result

x = torch.tensor([0.686, 2.164, 0.137], requires_grad = True)
alpha = 0.001
epsilon = 10
k = 0
print('Начальные координаты :', x.data)
print('')

while (epsilon >= 0.1):
  fx = function(x)
  fx.backward()
  gx = x.grad
  x_new = x - alpha*gx
  y = function(x_new)  
  y.backward()

  if fx <= y:
    alpha *= 0.7
  else:
    x.data = x_new
  epsilon = abs(fx-y)
  k += 1
  x.grad.zero_()
  print('Итерация :', k)
  print(epsilon)
  print(x.data)
  print('')
 
print('Всего итераций :', k)
print(x.data)

Начальные координаты : tensor([0.6860, 2.1640, 0.1370])

Итерация : 1
tensor(0.1098, grad_fn=<AbsBackward>)
tensor([0.6778, 2.1654, 0.1306])

Итерация : 2
tensor(0.1085, grad_fn=<AbsBackward>)
tensor([0.6696, 2.1667, 0.1243])

Итерация : 3
tensor(0.1073, grad_fn=<AbsBackward>)
tensor([0.6615, 2.1680, 0.1179])

Итерация : 4
tensor(0.1060, grad_fn=<AbsBackward>)
tensor([0.6535, 2.1694, 0.1116])

Итерация : 5
tensor(0.1048, grad_fn=<AbsBackward>)
tensor([0.6455, 2.1707, 0.1053])

Итерация : 6
tensor(0.1036, grad_fn=<AbsBackward>)
tensor([0.6376, 2.1720, 0.0990])

Итерация : 7
tensor(0.1024, grad_fn=<AbsBackward>)
tensor([0.6297, 2.1733, 0.0927])

Итерация : 8
tensor(0.1012, grad_fn=<AbsBackward>)
tensor([0.6219, 2.1746, 0.0865])

Итерация : 9
tensor(0.1001, grad_fn=<AbsBackward>)
tensor([0.6142, 2.1758, 0.0802])

Итерация : 10
tensor(0.0989, grad_fn=<AbsBackward>)
tensor([0.6065, 2.1771, 0.0740])

Всего итераций : 10
tensor([0.6065, 2.1771, 0.0740])


In [ ]:
#Проверка
def check(w,v):
  if w[0] <= v[0] and w[1] <= v[1] and w[2] <= v[2]:
    return 1
  else:
    return 0